apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::762513069016:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1WMB1VSCK8OLY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::762513069016:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-07T17:31:05Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-02-07T17:31:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1595"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2957328e-cf8c-443b-9167-78357b631f27
